# Generated by Django 4.2.23 on 2025-09-23 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("work", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Auto-generated invoice number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "sender_name",
                    models.CharField(
                        blank=True,
                        help_text="Sender name at time of invoice creation",
                        max_length=200,
                    ),
                ),
                (
                    "sender_address_line_1",
                    models.CharField(
                        blank=True,
                        help_text="Sender address line 1 at time of invoice creation",
                        max_length=200,
                    ),
                ),
                (
                    "sender_address_line_2",
                    models.CharField(
                        blank=True,
                        help_text="Sender address line 2 at time of invoice creation",
                        max_length=200,
                    ),
                ),
                (
                    "sender_town",
                    models.CharField(
                        blank=True,
                        help_text="Sender town at time of invoice creation",
                        max_length=100,
                    ),
                ),
                (
                    "sender_post_code",
                    models.CharField(
                        blank=True,
                        help_text="Sender post code at time of invoice creation",
                        max_length=20,
                    ),
                ),
                (
                    "sender_phone",
                    models.CharField(
                        blank=True,
                        help_text="Sender phone at time of invoice creation",
                        max_length=20,
                    ),
                ),
                (
                    "sender_email",
                    models.EmailField(
                        blank=True,
                        help_text="Sender email at time of invoice creation",
                        max_length=254,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        help_text="Bank name at time of invoice creation",
                        max_length=100,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        blank=True,
                        help_text="Account name at time of invoice creation",
                        max_length=100,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="Account number at time of invoice creation",
                        max_length=20,
                    ),
                ),
                (
                    "sort_code",
                    models.CharField(
                        blank=True,
                        help_text="Sort code at time of invoice creation",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="clients.client",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "work_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_line_items",
                        to="work.worklog",
                    ),
                ),
            ],
        ),
    ]
