# Generated by Django 4.2.23 on 2025-08-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='account_name',
            field=models.CharField(blank=True, help_text='Account name at time of invoice creation', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='account_number',
            field=models.CharField(blank=True, help_text='Account number at time of invoice creation', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name at time of invoice creation', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sender_address_line_1',
            field=models.CharField(blank=True, help_text='Sender address line 1 at time of invoice creation', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sender_address_line_2',
            field=models.CharField(blank=True, help_text='Sender address line 2 at time of invoice creation', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sender_email',
            field=models.EmailField(blank=True, help_text='Sender email at time of invoice creation', max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sender_name',
            field=models.CharField(blank=True, help_text='Sender name at time of invoice creation', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sender_phone',
            field=models.CharField(blank=True, help_text='Sender phone at time of invoice creation', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sender_post_code',
            field=models.CharField(blank=True, help_text='Sender post code at time of invoice creation', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sender_town',
            field=models.CharField(blank=True, help_text='Sender town at time of invoice creation', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sort_code',
            field=models.CharField(blank=True, help_text='Sort code at time of invoice creation', max_length=10),
        ),
    ]
