# Generated by Django 4.2.7 on 2025-01-27 15:20

from django.db import migrations, models
import django.db.models.deletion

def populate_default_categories(apps, schema_editor):
    Expense = apps.get_model('expenses', 'Expense')
    Category = apps.get_model('categories', 'Category')
    
    # Get or create a default "Other" expense category
    default_category, created = Category.objects.get_or_create(
        name='Other',
        defaults={
            'category_type': 'expense',
            'icon': 'fa-question-circle',
            'color': '#6c757d',
        }
    )
    
    # Update all expenses that don't have a category
    Expense.objects.filter(category__isnull=True).update(category=default_category)

def reverse_populate_default_categories(apps, schema_editor):
    # No need to reverse this operation
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_category'),
        ('categories', '0003_remove_description_and_active_fields'),
    ]

    operations = [
        # First populate existing expenses with default category
        migrations.RunPython(populate_default_categories, reverse_populate_default_categories),
        
        # Then make the field required
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='expenses',
                to='categories.category'
            ),
        ),
    ]
