# Generated by Django 4.2.23 on 2025-08-19 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='company_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='clients.client'),
        ),
    ]
