# Generated by Django 4.2.7 on 2025-01-27 15:20

from django.db import migrations

def create_default_categories(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')
    
    # Default expense categories
    expense_categories = [
        {'name': 'Food & Dining', 'category_type': 'expense', 'icon': 'fa-utensils', 'color': '#dc3545'},
        {'name': 'Transportation', 'category_type': 'expense', 'icon': 'fa-car', 'color': '#fd7e14'},
        {'name': 'Utilities', 'category_type': 'expense', 'icon': 'fa-bolt', 'color': '#ffc107'},
        {'name': 'Entertainment', 'category_type': 'expense', 'icon': 'fa-film', 'color': '#6f42c1'},
        {'name': 'Shopping', 'category_type': 'expense', 'icon': 'fa-shopping-bag', 'color': '#e83e8c'},
        {'name': 'Healthcare', 'category_type': 'expense', 'icon': 'fa-heartbeat', 'color': '#dc3545'},
        {'name': 'Housing', 'category_type': 'expense', 'icon': 'fa-home', 'color': '#28a745'},
        {'name': 'Work & Business', 'category_type': 'expense', 'icon': 'fa-briefcase', 'color': '#17a2b8'},
    ]
    
    # Default income categories
    income_categories = [
        {'name': 'Salary', 'category_type': 'income', 'icon': 'fa-money-bill-wave', 'color': '#28a745'},
        {'name': 'Freelance', 'category_type': 'income', 'icon': 'fa-laptop-code', 'color': '#17a2b8'},
        {'name': 'Investment', 'category_type': 'income', 'icon': 'fa-chart-line', 'color': '#6f42c1'},
        {'name': 'Other', 'category_type': 'income', 'icon': 'fa-plus-circle', 'color': '#6c757d'},
    ]
    
    # Default subscription categories
    subscription_categories = [
        {'name': 'Streaming Services', 'category_type': 'subscription', 'icon': 'fa-tv', 'color': '#e83e8c'},
        {'name': 'Software & Apps', 'category_type': 'subscription', 'icon': 'fa-mobile-alt', 'color': '#17a2b8'},
        {'name': 'Memberships', 'category_type': 'subscription', 'icon': 'fa-id-card', 'color': '#fd7e14'},
        {'name': 'Utilities', 'category_type': 'subscription', 'icon': 'fa-bolt', 'color': '#ffc107'},
    ]
    
    # Create all categories
    all_categories = expense_categories + income_categories + subscription_categories
    
    for cat_data in all_categories:
        Category.objects.get_or_create(
            name=cat_data['name'],
            defaults={
                'category_type': cat_data['category_type'],
                'icon': cat_data['icon'],
                'color': cat_data['color'],
            }
        )

def remove_default_categories(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')
    Category.objects.filter(description__startswith="Default").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories),
    ]
