# Generated by Django 4.2.23 on 2025-08-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_add_default_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
    ]
