# Generated by Django 4.2.23 on 2025-08-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='start_date',
        ),
    ]
