# Generated by Django 4.2.23 on 2025-09-28 09:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="attachment",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload invoices, receipts, or bank statements",
                max_length=255,
                null=True,
                verbose_name="attachment",
            ),
        ),
    ]
