# Generated by Django 4.2.7 on 2025-01-27 15:20

from django.db import migrations, models
import django.db.models.deletion

def populate_default_categories(apps, schema_editor):
    Income = apps.get_model('income', 'Income')
    Category = apps.get_model('categories', 'Category')
    
    # Get or create a default "Other" income category
    default_category, created = Category.objects.get_or_create(
        name='Other',
        defaults={
            'category_type': 'income',
            'icon': 'fa-question-circle',
            'color': '#6c757d',
        }
    )
    
    # Update all income entries that don't have a category
    Income.objects.filter(category__isnull=True).update(category=default_category)

def reverse_populate_default_categories(apps, schema_editor):
    # No need to reverse this operation
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_remove_income_category'),
        ('categories', '0003_remove_description_and_active_fields'),
    ]

    operations = [
        # First add the category field as nullable
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='income',
                to='categories.category'
            ),
        ),
        
        # Populate existing income entries with default category
        migrations.RunPython(populate_default_categories, reverse_populate_default_categories),
        
        # Then make the field required
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='income',
                to='categories.category'
            ),
        ),
        
        # Remove the notes field
        migrations.RemoveField(
            model_name='income',
            name='notes',
        ),
    ]
